version: '2'

networks:
  my_network:
    driver: bridge

services:

  server_app:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: server-app-container
    ports:
      - "8080:8080"
    networks:
      - my_network

  client_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-app-container
    ports:
      - "3000:3000"
    networks:
      - my_network

  nginx:
    image: nginx
    links:
      - server_app
      - client_app
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
    environment:
      VIRTUAL_HOST: 1562863-cd94457.twc1.net
      LETSENCRYPT_HOST: 1562863-cd94457.twc1.net
      LETSENCRYPT_EMAIL: l1zzard2444@gmail.com
    networks:
      - my_network

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - my_network

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    networks:
      - my_network