name: Create Remote Directory

on:
  push:
    branches:
      - main

jobs:
  create_directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          script: |
            mkdir /path/on/remote/new_directory