name: Update Docker Containers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Git Pull and Deploy
        run: |
          ssh -i ~/.ssh/id_rsa root@[$SERVER_IP] "cd /root/proj/Reactick && git pull && docker-compose up -d"
          ssh -i ~/.ssh/id_rsa root@[$SERVER_IP] "cd /root/proj/Reactick && git pull && docker-compose up -d --build"