name: Update Docker

on:
  push:
    branches:
      - main

jobs:
  update_directory:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          script: |
            cd ~/proj/Reactick
            git pull
            docker-compose down client_app server_app
            docker-compose up -d --build client_app server_app
            docker image prune -f