name: SSH and Docker Workflow

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_SECRET_KEY }}
        
    - name: Connect to Remote Server and Rebuild Docker Containers
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_SECRET_KEY }} root@${{ secrets.SERVER_IP }} "cd /proj/Reactick && docker-compose up -d --build"